server:
  port: ${PORT:8761}

spring:
  main:
    banner-mode: 'off'
  profiles.active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
      name: discovery-service


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      enableSelfPreservation: false






